### ISSUE TITLE
How to relate the json file to the original NIH image?

### ISSUE THREAD

**Issue by LLYXC** [Deepwise-AILab/ChestX-Det-Dataset#2]
Dear authors, 

Many thanks for the sharing and contribution to the community. I found that the names of the images in the json file are not the same as those in the NIH ChestX-14 dataset. I wonder is there a way to link these ids to the original NIH ChestX-14 ids?

**Comment by jeline0110** [comment]
[mapping.json.zip](https://github.com/Deepwise-AILab/ChestX-Det-Dataset/files/7632367/mapping.json.zip)

**Comment by LLYXC** [comment]
Many thanks for your reply!
